// prisma/reset.ts
import { Pool } from "pg"
import * as dotenv from "dotenv"

// Load environment variables
dotenv.config()

// Get database connection
const databaseUrl = process.env.POSTGRES_PRISMA_URL || process.env.DATABASE_URL

if (!databaseUrl) {
  console.error("❌ Error: POSTGRES_PRISMA_URL or DATABASE_URL environment variable is not set")
  process.exit(1)
}

// Parse connection string
const url = new URL(databaseUrl)
const isSupabase = url.hostname.includes("supabase") || url.hostname.includes("pooler")

const pool = new Pool({
  host: url.hostname,
  port: parseInt(url.port) || 5432,
  database: url.pathname.slice(1),
  user: url.username,
  password: url.password,
  ssl: isSupabase ? { rejectUnauthorized: false } : undefined,
})

const pokemonData = [
  {
    name: "Charizard",
    spriteUrl: "/charizard-pokemon.png",
    typePrimary: "Fire",
    typeSecondary: "Flying",
    hp: 78,
    attack: 84,
    defense: 78,
    specialAttack: 109,
    specialDefense: 85,
    speed: 100,
  },
  {
    name: "Blastoise",
    spriteUrl: "/blastoise-pokemon.jpg",
    typePrimary: "Water",
    typeSecondary: null,
    hp: 79,
    attack: 83,
    defense: 100,
    specialAttack: 85,
    specialDefense: 105,
    speed: 78,
  },
  {
    name: "Venusaur",
    spriteUrl: "/venusaur-pokemon.png",
    typePrimary: "Grass",
    typeSecondary: "Poison",
    hp: 80,
    attack: 82,
    defense: 83,
    specialAttack: 100,
    specialDefense: 100,
    speed: 80,
  },
  {
    name: "Pikachu",
    spriteUrl: "/pikachu-pokemon.jpg",
    typePrimary: "Electric",
    typeSecondary: null,
    hp: 35,
    attack: 55,
    defense: 40,
    specialAttack: 50,
    specialDefense: 50,
    speed: 90,
  },
  {
    name: "Gengar",
    spriteUrl: "/gengar-pokemon.jpg",
    typePrimary: "Ghost",
    typeSecondary: "Poison",
    hp: 60,
    attack: 65,
    defense: 60,
    specialAttack: 130,
    specialDefense: 75,
    speed: 110,
  },
  {
    name: "Dragonite",
    spriteUrl: "/dragonite-pokemon.jpg",
    typePrimary: "Dragon",
    typeSecondary: "Flying",
    hp: 91,
    attack: 134,
    defense: 95,
    specialAttack: 100,
    specialDefense: 100,
    speed: 80,
  },
  {
    name: "Alakazam",
    spriteUrl: "/alakazam-pokemon.jpg",
    typePrimary: "Psychic",
    typeSecondary: null,
    hp: 55,
    attack: 50,
    defense: 45,
    specialAttack: 135,
    specialDefense: 95,
    speed: 120,
  },
  {
    name: "Machamp",
    spriteUrl: "/machamp-pokemon.jpg",
    typePrimary: "Fighting",
    typeSecondary: null,
    hp: 90,
    attack: 130,
    defense: 80,
    specialAttack: 65,
    specialDefense: 85,
    speed: 55,
  },
  {
    name: "Lapras",
    spriteUrl: "/lapras-pokemon.jpg",
    typePrimary: "Water",
    typeSecondary: "Ice",
    hp: 130,
    attack: 85,
    defense: 80,
    specialAttack: 85,
    specialDefense: 95,
    speed: 60,
  },
  {
    name: "Gyarados",
    spriteUrl: "/gyarados-pokemon.jpg",
    typePrimary: "Water",
    typeSecondary: "Flying",
    hp: 95,
    attack: 125,
    defense: 79,
    specialAttack: 60,
    specialDefense: 100,
    speed: 81,
  },
  {
    name: "Mewtwo",
    spriteUrl: "/mewtwo-pokemon.jpg",
    typePrimary: "Psychic",
    typeSecondary: null,
    hp: 106,
    attack: 110,
    defense: 90,
    specialAttack: 154,
    specialDefense: 90,
    speed: 130,
  },
  {
    name: "Articuno",
    spriteUrl: "/articuno-pokemon.jpg",
    typePrimary: "Ice",
    typeSecondary: "Flying",
    hp: 90,
    attack: 85,
    defense: 100,
    specialAttack: 95,
    specialDefense: 125,
    speed: 85,
  },
  {
    name: "Zapdos",
    spriteUrl: "/zapdos-pokemon.jpg",
    typePrimary: "Electric",
    typeSecondary: "Flying",
    hp: 90,
    attack: 90,
    defense: 85,
    specialAttack: 125,
    specialDefense: 90,
    speed: 100,
  },
  {
    name: "Moltres",
    spriteUrl: "/moltres-pokemon.jpg",
    typePrimary: "Fire",
    typeSecondary: "Flying",
    hp: 90,
    attack: 100,
    defense: 90,
    specialAttack: 125,
    specialDefense: 85,
    speed: 90,
  },
  {
    name: "Snorlax",
    spriteUrl: "/snorlax-pokemon.jpg",
    typePrimary: "Normal",
    typeSecondary: null,
    hp: 160,
    attack: 110,
    defense: 65,
    specialAttack: 65,
    specialDefense: 110,
    speed: 30,
  },
  {
    name: "Umbreon",
    spriteUrl: "/umbreon-pokemon.jpg",
    typePrimary: "Dark",
    typeSecondary: null,
    hp: 95,
    attack: 65,
    defense: 110,
    specialAttack: 60,
    specialDefense: 130,
    speed: 65,
  },
  {
    name: "Espeon",
    spriteUrl: "/espeon-pokemon.jpg",
    typePrimary: "Psychic",
    typeSecondary: null,
    hp: 65,
    attack: 65,
    defense: 60,
    specialAttack: 130,
    specialDefense: 95,
    speed: 110,
  },
  {
    name: "Tyranitar",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/248.png",
    typePrimary: "Rock",
    typeSecondary: "Dark",
    hp: 100,
    attack: 134,
    defense: 110,
    specialAttack: 95,
    specialDefense: 100,
    speed: 61,
  },
  {
    name: "Lucario",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png",
    typePrimary: "Fighting",
    typeSecondary: "Steel",
    hp: 70,
    attack: 110,
    defense: 70,
    specialAttack: 115,
    specialDefense: 70,
    speed: 90,
  },
  {
    name: "Gardevoir",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/282.png",
    typePrimary: "Psychic",
    typeSecondary: "Fairy",
    hp: 68,
    attack: 65,
    defense: 65,
    specialAttack: 125,
    specialDefense: 115,
    speed: 80,
  },
  {
    name: "Glaceon",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/471.png",
    typePrimary: "Ice",
    typeSecondary: null,
    hp: 65,
    attack: 60,
    defense: 110,
    specialAttack: 130,
    specialDefense: 95,
    speed: 65,
  },
  {
    name: "Sylveon",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/700.png",
    typePrimary: "Fairy",
    typeSecondary: null,
    hp: 95,
    attack: 65,
    defense: 65,
    specialAttack: 110,
    specialDefense: 130,
    speed: 60,
  },
  // Additional 28 popular Pokemon
  {
    name: "Rayquaza",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/384.png",
    typePrimary: "Dragon",
    typeSecondary: "Flying",
    hp: 105,
    attack: 150,
    defense: 90,
    specialAttack: 150,
    specialDefense: 90,
    speed: 95,
  },
  {
    name: "Metagross",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/376.png",
    typePrimary: "Steel",
    typeSecondary: "Psychic",
    hp: 80,
    attack: 135,
    defense: 130,
    specialAttack: 95,
    specialDefense: 90,
    speed: 70,
  },
  {
    name: "Salamence",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/373.png",
    typePrimary: "Dragon",
    typeSecondary: "Flying",
    hp: 95,
    attack: 135,
    defense: 80,
    specialAttack: 110,
    specialDefense: 80,
    speed: 100,
  },
  {
    name: "Garchomp",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/445.png",
    typePrimary: "Dragon",
    typeSecondary: "Ground",
    hp: 108,
    attack: 130,
    defense: 95,
    specialAttack: 80,
    specialDefense: 85,
    speed: 102,
  },
  {
    name: "Infernape",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/392.png",
    typePrimary: "Fire",
    typeSecondary: "Fighting",
    hp: 76,
    attack: 104,
    defense: 71,
    specialAttack: 104,
    specialDefense: 71,
    speed: 108,
  },
  {
    name: "Empoleon",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/395.png",
    typePrimary: "Water",
    typeSecondary: "Steel",
    hp: 84,
    attack: 86,
    defense: 88,
    specialAttack: 111,
    specialDefense: 101,
    speed: 60,
  },
  {
    name: "Torterra",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/389.png",
    typePrimary: "Grass",
    typeSecondary: "Ground",
    hp: 95,
    attack: 109,
    defense: 105,
    specialAttack: 75,
    specialDefense: 85,
    speed: 56,
  },
  {
    name: "Luxray",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/405.png",
    typePrimary: "Electric",
    typeSecondary: null,
    hp: 80,
    attack: 120,
    defense: 79,
    specialAttack: 95,
    specialDefense: 79,
    speed: 70,
  },
  {
    name: "Staraptor",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/398.png",
    typePrimary: "Normal",
    typeSecondary: "Flying",
    hp: 85,
    attack: 120,
    defense: 70,
    specialAttack: 50,
    specialDefense: 60,
    speed: 100,
  },
  {
    name: "Roserade",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/407.png",
    typePrimary: "Grass",
    typeSecondary: "Poison",
    hp: 60,
    attack: 70,
    defense: 65,
    specialAttack: 125,
    specialDefense: 105,
    speed: 90,
  },
  {
    name: "Weavile",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/461.png",
    typePrimary: "Dark",
    typeSecondary: "Ice",
    hp: 70,
    attack: 120,
    defense: 65,
    specialAttack: 45,
    specialDefense: 85,
    speed: 125,
  },
  {
    name: "Magnezone",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/462.png",
    typePrimary: "Electric",
    typeSecondary: "Steel",
    hp: 70,
    attack: 70,
    defense: 115,
    specialAttack: 130,
    specialDefense: 90,
    speed: 60,
  },
  {
    name: "Togekiss",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/468.png",
    typePrimary: "Fairy",
    typeSecondary: "Flying",
    hp: 85,
    attack: 50,
    defense: 95,
    specialAttack: 120,
    specialDefense: 115,
    speed: 80,
  },
  {
    name: "Gliscor",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/472.png",
    typePrimary: "Ground",
    typeSecondary: "Flying",
    hp: 75,
    attack: 95,
    defense: 125,
    specialAttack: 45,
    specialDefense: 75,
    speed: 95,
  },
  {
    name: "Mamoswine",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/473.png",
    typePrimary: "Ice",
    typeSecondary: "Ground",
    hp: 110,
    attack: 130,
    defense: 80,
    specialAttack: 70,
    specialDefense: 60,
    speed: 80,
  },
  {
    name: "Porygon-Z",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/474.png",
    typePrimary: "Normal",
    typeSecondary: null,
    hp: 85,
    attack: 80,
    defense: 70,
    specialAttack: 135,
    specialDefense: 75,
    speed: 90,
  },
  {
    name: "Gallade",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/475.png",
    typePrimary: "Psychic",
    typeSecondary: "Fighting",
    hp: 68,
    attack: 125,
    defense: 65,
    specialAttack: 65,
    specialDefense: 115,
    speed: 80,
  },
  {
    name: "Dusknoir",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/477.png",
    typePrimary: "Ghost",
    typeSecondary: null,
    hp: 45,
    attack: 100,
    defense: 135,
    specialAttack: 65,
    specialDefense: 135,
    speed: 45,
  },
  {
    name: "Froslass",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/478.png",
    typePrimary: "Ice",
    typeSecondary: "Ghost",
    hp: 70,
    attack: 80,
    defense: 70,
    specialAttack: 80,
    specialDefense: 70,
    speed: 110,
  },
  {
    name: "Rotom",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/479.png",
    typePrimary: "Electric",
    typeSecondary: "Ghost",
    hp: 50,
    attack: 65,
    defense: 107,
    specialAttack: 105,
    specialDefense: 107,
    speed: 86,
  },
  {
    name: "Giratina",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/487.png",
    typePrimary: "Ghost",
    typeSecondary: "Dragon",
    hp: 150,
    attack: 100,
    defense: 120,
    specialAttack: 100,
    specialDefense: 120,
    speed: 90,
  },
  {
    name: "Darkrai",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/491.png",
    typePrimary: "Dark",
    typeSecondary: null,
    hp: 70,
    attack: 90,
    defense: 90,
    specialAttack: 135,
    specialDefense: 90,
    speed: 125,
  },
  {
    name: "Arceus",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493.png",
    typePrimary: "Normal",
    typeSecondary: null,
    hp: 120,
    attack: 120,
    defense: 120,
    specialAttack: 120,
    specialDefense: 120,
    speed: 120,
  },
  {
    name: "Dialga",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/483.png",
    typePrimary: "Steel",
    typeSecondary: "Dragon",
    hp: 100,
    attack: 120,
    defense: 120,
    specialAttack: 150,
    specialDefense: 100,
    speed: 90,
  },
  {
    name: "Palkia",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/484.png",
    typePrimary: "Water",
    typeSecondary: "Dragon",
    hp: 90,
    attack: 120,
    defense: 100,
    specialAttack: 150,
    specialDefense: 120,
    speed: 100,
  },
  {
    name: "Heatran",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/485.png",
    typePrimary: "Fire",
    typeSecondary: "Steel",
    hp: 91,
    attack: 90,
    defense: 106,
    specialAttack: 130,
    specialDefense: 106,
    speed: 77,
  },
  {
    name: "Scizor",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/212.png",
    typePrimary: "Bug",
    typeSecondary: "Steel",
    hp: 70,
    attack: 130,
    defense: 100,
    specialAttack: 55,
    specialDefense: 80,
    speed: 65,
  },
  {
    name: "Hydreigon",
    spriteUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/635.png",
    typePrimary: "Dark",
    typeSecondary: "Dragon",
    hp: 92,
    attack: 105,
    defense: 90,
    specialAttack: 125,
    specialDefense: 90,
    speed: 98,
  },
]

async function main() {
  console.log("🗑️  Clearing database...")

  // Delete all Pokemon records using raw SQL
  const deleteResult = await pool.query('DELETE FROM "Pokemon"')
  console.log(`   Deleted ${deleteResult.rowCount} Pokemon records`)

  console.log("🌱 Seeding database...")

  // Create all Pokemon records using raw SQL
  // Note: Column names must match the Prisma schema (camelCase with quotes)
  for (const pokemon of pokemonData) {
    await pool.query(
      `INSERT INTO "Pokemon" (name, "spriteUrl", "typePrimary", "typeSecondary", hp, attack, defense, "specialAttack", "specialDefense", speed)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
       ON CONFLICT (name) DO UPDATE SET
         "spriteUrl" = EXCLUDED."spriteUrl",
         "typePrimary" = EXCLUDED."typePrimary",
         "typeSecondary" = EXCLUDED."typeSecondary",
         hp = EXCLUDED.hp,
         attack = EXCLUDED.attack,
         defense = EXCLUDED.defense,
         "specialAttack" = EXCLUDED."specialAttack",
         "specialDefense" = EXCLUDED."specialDefense",
         speed = EXCLUDED.speed`,
      [
        pokemon.name,
        pokemon.spriteUrl,
        pokemon.typePrimary,
        pokemon.typeSecondary,
        pokemon.hp,
        pokemon.attack,
        pokemon.defense,
        pokemon.specialAttack,
        pokemon.specialDefense,
        pokemon.speed,
      ]
    )
  }

  console.log(`✅ Successfully seeded ${pokemonData.length} Pokémon`)
  console.log("🎉 Database reset and seeded!")
}

main()
  .catch((e) => {
    console.error("❌ Reset failed:", e)
    process.exit(1)
  })
  .finally(async () => {
    await pool.end()
  })

